In [197]:
import sys
import copy
import pickle as pk
import pandas as pd
from IPython.display import display

curr_game_states = None

# A snapshot of a single frame within a game along with the final win_outcome at that frame
class BoardState:
    def __init__(self, board_state, win_outcome_list = []):
        self.board_state = board_state
        self.win_outcome_list = win_outcome_list
        
    def get_board_state(self):
        return self.board_state
    
    def get_win_outcome_list(self):
        return self.win_outcome_list
    
    def add_win_outcome_to_list(self, new_win_outcome):
        self.win_outcome_list.append(new_win_outcome)

# Contains the entire game in a list of BoardState objects
class OthelloGameStates:
    board_state_obj_list = []
    
    def __init__(self, board_state_obj):
        self.board_state_obj_list.append(board_state_obj)
        
    def add_board_state_obj_to_list(self, board_state_obj):
        self.board_state_obj_list.append(board_state_obj)
        
    def get_board_state_obj_list(self):
        return self.board_state_obj_list
    
    def get_count(self):
        return len(self.board_state_obj_list)
    
# init grid state, where -1 is empty cell, 0 is black, 1 is white
grid = [[-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, 1, 0, -1, -1, -1],
        [-1, -1, -1, 0, 1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1]]

init_board_state = BoardState(grid)
curr_game_states = OthelloGameStates(init_board_state)
# Assignment statements in Python do not copy objects, they create bindings between a target and an object.

# Construct a key from board layout and then save board layout obj under it
temp_key = []
for i in range(8):
    for j in range(8):
        temp_key.append(str(grid[i][j]))
key = ''.join(temp_key)
new_game_states_dict = {key : init_board_state}

In [198]:
count = curr_game_states.get_count()
for i in range(count):
    state = curr_game_states.get_board_state_obj_list()[i]
    df = pd.DataFrame(state.get_board_state())
    display(df)
    print("[ frame", count, ", win-outcome list =>", state.get_win_outcome_list(), "]")

   0  1  2  3  4  5  6  7
0 -1 -1 -1 -1 -1 -1 -1 -1
1 -1 -1 -1 -1 -1 -1 -1 -1
2 -1 -1 -1 -1 -1 -1 -1 -1
3 -1 -1 -1  1  0 -1 -1 -1
4 -1 -1 -1  0  1 -1 -1 -1
5 -1 -1 -1 -1 -1 -1 -1 -1
6 -1 -1 -1 -1 -1 -1 -1 -1
7 -1 -1 -1 -1 -1 -1 -1 -1

[ frame 1 , win-outcome list => [] ]

In [199]:
with open("Datasets/David/30x50_w.txt","r") as raw_input:
    for input_contents in raw_input:
        curr_board_grid = copy.deepcopy(curr_game_states.get_board_state_obj_list()[count-1].get_board_state())
        color, x, y = input_contents.split()
        int_color = int(color)
        if curr_board_grid[int(y)][int(x)] == -1:
            curr_board_grid[int(y)][int(x)] = int_color
            # TODO: Potential breakage: Placing a piece on a blank square but not sandwiching opponent's piece(s)
            print("Placing a", int_color, "piece @", x, y)
            a = copy.deepcopy(int(x))
            b = copy.deepcopy(int(x))
            c = copy.deepcopy(int(y))
            d = copy.deepcopy(int(y))
            
            # Vars for diagonal movement
            x1 = copy.deepcopy(int(x))
            x2 = copy.deepcopy(int(x))
            x3 = copy.deepcopy(int(x))
            x4 = copy.deepcopy(int(x))
            y1 = copy.deepcopy(int(y))
            y2 = copy.deepcopy(int(y))
            y3 = copy.deepcopy(int(y))
            y4 = copy.deepcopy(int(y))
            
            # Left movement, decreasing col index = left movement
            left_flag = False
            while a-1 >= 0 and curr_board_grid[int(y)][a-1] != -1:
                print("Can move left")
                if curr_board_grid[int(y)][a-1] == int_color:
                    left_flag = True
                    break
                else:
                    a = a-1
            a = copy.deepcopy(int(x))
            if left_flag:  # Initiate left movement
                while a-1 >= 0 and curr_board_grid[int(y)][a-1] != -1:
                    if curr_board_grid[int(y)][a-1] == int_color:
                        break
                    else:
                        curr_board_grid[int(y)][a-1] = int_color
                        a = a-1
                        
            # Right movement, increasing col index = right movement
            right_flag = False
            while b+1 <= 7 and curr_board_grid[int(y)][b+1] != -1:
                print("Can move right")
                if curr_board_grid[int(y)][b+1] == int_color:
                    right_flag = True
                    break
                else:
                    b = b+1
            b = copy.deepcopy(int(x))
            if right_flag:  # Initiate right movement
                while b+1 <= 7 and curr_board_grid[int(y)][b+1] != -1:
                    if curr_board_grid[int(y)][b+1] == int_color:
                        break
                    else:
                        curr_board_grid[int(y)][b+1] = int_color
                        b = b+1
                    
            # Up movement, decreasing row index = upward movement
            up_flag = False
            while c-1 >= 0 and curr_board_grid[c-1][int(x)] != -1:
                print("Can move up")
                if curr_board_grid[c-1][int(x)] == int_color:
                    up_flag = True
                    break
                else:
                    c = c-1
            c = copy.deepcopy(int(y))
            if up_flag:  # Initiate upward movement
                while c-1 >=0 and curr_board_grid[c-1][int(x)] != -1:
                    if curr_board_grid[c-1][int(x)] == int_color:
                        break
                    else:
                        curr_board_grid[c-1][int(x)] = int_color
                        c = c-1        
                    
            # Down movement, increasing row index = downward movement
            down_flag = False
            while d+1 <= 7 and curr_board_grid[d+1][int(x)] != -1:
                print("Can move down")
                if curr_board_grid[d+1][int(x)] == int_color:
                    down_flag = True
                    break
                else:
                    d = d+1
            d = copy.deepcopy(int(y))
            if down_flag:  # Initiate downward movement
                while d+1 <= 7 and curr_board_grid[d+1][int(x)] != -1:
                    if curr_board_grid[d+1][int(x)] == int_color:
                        break
                    else:
                        curr_board_grid[d+1][int(x)] = int_color
                        d = d+1
                        
            # Upper-left movement, decreasing col index = left movement, decreasing row index = upward movement
            upper_left_flag = False
            while x1-1 >= 0 and y1-1 >= 0 and curr_board_grid[y1-1][x1-1] != -1:
                print("Can move upper-left")
                if curr_board_grid[y1-1][x1-1] == int_color:
                    upper_left_flag = True
                    break
                else:
                    x1 = x1-1
                    y1 = y1-1
            x1 = copy.deepcopy(int(x))
            y1 = copy.deepcopy(int(y))
            if upper_left_flag:  # Initiate upper-left movement
                while x1-1 >= 0 and y1-1 >= 0 and curr_board_grid[y1-1][x1-1] != -1:
                    if curr_board_grid[y1-1][x1-1] == int_color:
                        break
                    else:
                        curr_board_grid[y1-1][x1-1] = int_color
                        x1 = x1-1
                        y1 = y1-1
                      
            # Upper-right movement, increasing col index = right movement, decreasing row index = upward movement
            upper_right_flag = False
            while x2+1 <= 7 and y2-1 >= 0 and curr_board_grid[y2-1][x2+1] != -1:
                print("Can move upper-right")
                if curr_board_grid[y2-1][x2+1] == int_color:
                    upper_right_flag = True
                    break
                else:
                    x2 = x2+1
                    y2 = y2-1
            x2 = copy.deepcopy(int(x))
            y2 = copy.deepcopy(int(y))
            if upper_right_flag:  # Initiate upper-right movement
                while x2+1 <= 7 and y2-1 >= 0 and curr_board_grid[y2-1][x2+1] != -1:
                    if curr_board_grid[y2-1][x2+1] == int_color:
                        break
                    else:
                        curr_board_grid[y2-1][x2+1] = int_color
                        x2 = x2+1
                        y2 = y2-1
            
            # Lower-left movement, decreasing col index = left movement, increasing row index = downward movement
            lower_left_flag = False
            while x3-1 >= 0 and y3+1 <= 7 and curr_board_grid[y3+1][x3-1] != -1:
                print("Can move lower-left")
                if curr_board_grid[y3+1][x3-1] == int_color:
                    lower_left_flag = True
                    break
                else:
                    x3 = x3-1
                    y3 = y3+1
            x3 = copy.deepcopy(int(x))
            y3 = copy.deepcopy(int(y))
            if lower_left_flag:  # Initiate lower-left movement
                while x3-1 >= 0 and y3+1 <= 7 and curr_board_grid[y3+1][x3-1] != -1:
                    if curr_board_grid[y3+1][x3-1] == int_color:
                        break
                    else:
                        curr_board_grid[y3+1][x3-1] = int_color
                        x3 = x3-1
                        y3 = y3+1
                      
            # Lower-right movement, increasing col index = right movement, increasing row index = downward movement
            lower_right_flag = False
            while x4+1 <= 7 and y4+1 <= 7 and curr_board_grid[y4+1][x4+1] != -1:
                print("Can move lower-right")
                if curr_board_grid[y4+1][x4+1] == int_color:
                    lower_right_flag = True
                    break
                else:
                    x4 = x4+1
                    y4 = y4+1
            x4 = copy.deepcopy(int(x))
            y4 = copy.deepcopy(int(y))
            if lower_right_flag:  # Initiate lower-right movement
                while x4+1 <= 7 and y4+1 <= 7 and curr_board_grid[y4+1][x4+1] != -1:
                    if curr_board_grid[y4+1][x4+1] == int_color:
                        break
                    else:
                        curr_board_grid[y4+1][x4+1] = int_color
                        x4 = x4+1
                        y4 = y4+1
                      
            # Adding game state to curr_game_states after 1 move
            new_board_state = BoardState(curr_board_grid)
            curr_game_states.add_board_state_obj_to_list(new_board_state)
            count = curr_game_states.get_count()
            state = curr_game_states.get_board_state_obj_list()[count-1]
            df = pd.DataFrame(state.get_board_state())
            display(df)
            print("[ frame", count, ", win-outome list =>", state.get_win_outcome_list(), "]")
            print()
        else: 
            print("Error: Attempting to place a piece on an occupied cell.", file=sys.stderr)

Placing a 0 piece @ 5 4
Can move left
Can move left
Can move upper-left

   0  1  2  3  4  5  6  7
0 -1 -1 -1 -1 -1 -1 -1 -1
1 -1 -1 -1 -1 -1 -1 -1 -1
2 -1 -1 -1 -1 -1 -1 -1 -1
3 -1 -1 -1  1  0 -1 -1 -1
4 -1 -1 -1  0  0  0 -1 -1
5 -1 -1 -1 -1 -1 -1 -1 -1
6 -1 -1 -1 -1 -1 -1 -1 -1
7 -1 -1 -1 -1 -1 -1 -1 -1

[ frame 2 , win-outome list => [] ]

Placing a 1 piece @ 5 5
Can move up
Can move upper-left
Can move upper-left

   0  1  2  3  4  5  6  7
0 -1 -1 -1 -1 -1 -1 -1 -1
1 -1 -1 -1 -1 -1 -1 -1 -1
2 -1 -1 -1 -1 -1 -1 -1 -1
3 -1 -1 -1  1  0 -1 -1 -1
4 -1 -1 -1  0  1  0 -1 -1
5 -1 -1 -1 -1 -1  1 -1 -1
6 -1 -1 -1 -1 -1 -1 -1 -1
7 -1 -1 -1 -1 -1 -1 -1 -1

[ frame 3 , win-outome list => [] ]

Placing a 0 piece @ 4 5
Can move right
Can move up
Can move up
Can move upper-left
Can move upper-right

   0  1  2  3  4  5  6  7
0 -1 -1 -1 -1 -1 -1 -1 -1
1 -1 -1 -1 -1 -1 -1 -1 -1
2 -1 -1 -1 -1 -1 -1 -1 -1
3 -1 -1 -1  1  0 -1 -1 -1
4 -1 -1 -1  0  0  0 -1 -1
5 -1 -1 -1 -1  0  1 -1 -1
6 -1 -1 -1 -1 -1 -1 -1 -1
7 -1 -1 -1 -1 -1 -1 -1 -1

[ frame 4 , win-outome list => [] ]

Placing a 1 piece @ 3 5
Can move right
Can move right
Can move up
Can move up
Can move upper-right

   0  1  2  3  4  5  6  7
0 -1 -1 -1 -1 -1 -1 -1 -1
1 -1 -1 -1 -1 -1 -1 -1 -1
2 -1 -1 -1 -1 -1 -1 -1 -1
3 -1 -1 -1  1  0 -1 -1 -1
4 -1 -1 -1  1  0  0 -1 -1
5 -1 -1 -1  1  1  1 -1 -1
6 -1 -1 -1 -1 -1 -1 -1 -1
7 -1 -1 -1 -1 -1 -1 -1 -1

[ frame 5 , win-outome list => [] ]

Placing a 0 piece @ 2 4
Can move right
Can move right
Can move upper-right
Can move lower-right

   0  1  2  3  4  5  6  7
0 -1 -1 -1 -1 -1 -1 -1 -1
1 -1 -1 -1 -1 -1 -1 -1 -1
2 -1 -1 -1 -1 -1 -1 -1 -1
3 -1 -1 -1  1  0 -1 -1 -1
4 -1 -1  0  0  0  0 -1 -1
5 -1 -1 -1  1  1  1 -1 -1
6 -1 -1 -1 -1 -1 -1 -1 -1
7 -1 -1 -1 -1 -1 -1 -1 -1

[ frame 6 , win-outome list => [] ]

Placing a 1 piece @ 5 3
Can move left
Can move left
Can move down
Can move down
Can move lower-left
Can move lower-left

   0  1  2  3  4  5  6  7
0 -1 -1 -1 -1 -1 -1 -1 -1
1 -1 -1 -1 -1 -1 -1 -1 -1
2 -1 -1 -1 -1 -1 -1 -1 -1
3 -1 -1 -1  1  1  1 -1 -1
4 -1 -1  0  0  1  1 -1 -1
5 -1 -1 -1  1  1  1 -1 -1
6 -1 -1 -1 -1 -1 -1 -1 -1
7 -1 -1 -1 -1 -1 -1 -1 -1

[ frame 7 , win-outome list => [] ]

Placing a 0 piece @ 3 2
Can move down
Can move down
Can move lower-right
Can move lower-right

   0  1  2  3  4  5  6  7
0 -1 -1 -1 -1 -1 -1 -1 -1
1 -1 -1 -1 -1 -1 -1 -1 -1
2 -1 -1 -1  0 -1 -1 -1 -1
3 -1 -1 -1  0  1  1 -1 -1
4 -1 -1  0  0  1  1 -1 -1
5 -1 -1 -1  1  1  1 -1 -1
6 -1 -1 -1 -1 -1 -1 -1 -1
7 -1 -1 -1 -1 -1 -1 -1 -1

[ frame 8 , win-outome list => [] ]

Placing a 1 piece @ 2 5
Can move right
Can move up
Can move upper-right
Can move upper-right

   0  1  2  3  4  5  6  7
0 -1 -1 -1 -1 -1 -1 -1 -1
1 -1 -1 -1 -1 -1 -1 -1 -1
2 -1 -1 -1  0 -1 -1 -1 -1
3 -1 -1 -1  0  1  1 -1 -1
4 -1 -1  0  1  1  1 -1 -1
5 -1 -1  1  1  1  1 -1 -1
6 -1 -1 -1 -1 -1 -1 -1 -1
7 -1 -1 -1 -1 -1 -1 -1 -1

[ frame 9 , win-outome list => [] ]

Placing a 0 piece @ 2 6
Can move up
Can move up
Can move upper-right
Can move upper-right
Can move upper-right

   0  1  2  3  4  5  6  7
0 -1 -1 -1 -1 -1 -1 -1 -1
1 -1 -1 -1 -1 -1 -1 -1 -1
2 -1 -1 -1  0 -1 -1 -1 -1
3 -1 -1 -1  0  1  1 -1 -1
4 -1 -1  0  1  1  1 -1 -1
5 -1 -1  0  1  1  1 -1 -1
6 -1 -1  0 -1 -1 -1 -1 -1
7 -1 -1 -1 -1 -1 -1 -1 -1

[ frame 10 , win-outome list => [] ]

Placing a 1 piece @ 2 2
Can move right
Can move lower-right
Can move lower-right

   0  1  2  3  4  5  6  7
0 -1 -1 -1 -1 -1 -1 -1 -1
1 -1 -1 -1 -1 -1 -1 -1 -1
2 -1 -1  1  0 -1 -1 -1 -1
3 -1 -1 -1  1  1  1 -1 -1
4 -1 -1  0  1  1  1 -1 -1
5 -1 -1  0  1  1  1 -1 -1
6 -1 -1  0 -1 -1 -1 -1 -1
7 -1 -1 -1 -1 -1 -1 -1 -1

[ frame 11 , win-outome list => [] ]

Placing a 0 piece @ 4 2
Can move left
Can move down
Can move down
Can move down
Can move lower-left
Can move lower-left
Can move lower-right

   0  1  2  3  4  5  6  7
0 -1 -1 -1 -1 -1 -1 -1 -1
1 -1 -1 -1 -1 -1 -1 -1 -1
2 -1 -1  1  0  0 -1 -1 -1
3 -1 -1 -1  0  1  1 -1 -1
4 -1 -1  0  1  1  1 -1 -1
5 -1 -1  0  1  1  1 -1 -1
6 -1 -1  0 -1 -1 -1 -1 -1
7 -1 -1 -1 -1 -1 -1 -1 -1

[ frame 12 , win-outome list => [] ]

Placing a 1 piece @ 5 2
Can move left
Can move left
Can move left
Can move down
Can move lower-left

   0  1  2  3  4  5  6  7
0 -1 -1 -1 -1 -1 -1 -1 -1
1 -1 -1 -1 -1 -1 -1 -1 -1
2 -1 -1  1  1  1  1 -1 -1
3 -1 -1 -1  0  1  1 -1 -1
4 -1 -1  0  1  1  1 -1 -1
5 -1 -1  0  1  1  1 -1 -1
6 -1 -1  0 -1 -1 -1 -1 -1
7 -1 -1 -1 -1 -1 -1 -1 -1

[ frame 13 , win-outome list => [] ]

Placing a 0 piece @ 3 6
Can move left
Can move up
Can move up
Can move up
Can move upper-left
Can move upper-right
Can move upper-right

   0  1  2  3  4  5  6  7
0 -1 -1 -1 -1 -1 -1 -1 -1
1 -1 -1 -1 -1 -1 -1 -1 -1
2 -1 -1  1  1  1  1 -1 -1
3 -1 -1 -1  0  1  1 -1 -1
4 -1 -1  0  0  1  1 -1 -1
5 -1 -1  0  0  1  1 -1 -1
6 -1 -1  0  0 -1 -1 -1 -1
7 -1 -1 -1 -1 -1 -1 -1 -1

[ frame 14 , win-outome list => [] ]

Placing a 1 piece @ 2 3
Can move right
Can move right
Can move up
Can move down
Can move down
Can move down
Can move upper-right
Can move lower-right
Can move lower-right

   0  1  2  3  4  5  6  7
0 -1 -1 -1 -1 -1 -1 -1 -1
1 -1 -1 -1 -1 -1 -1 -1 -1
2 -1 -1  1  1  1  1 -1 -1
3 -1 -1  1  1  1  1 -1 -1
4 -1 -1  0  1  1  1 -1 -1
5 -1 -1  0  0  1  1 -1 -1
6 -1 -1  0  0 -1 -1 -1 -1
7 -1 -1 -1 -1 -1 -1 -1 -1

[ frame 15 , win-outome list => [] ]

Placing a 0 piece @ 6 4
Can move left
Can move left
Can move left
Can move left
Can move upper-left
Can move upper-left
Can move lower-left

   0  1  2  3  4  5  6  7
0 -1 -1 -1 -1 -1 -1 -1 -1
1 -1 -1 -1 -1 -1 -1 -1 -1
2 -1 -1  1  1  1  1 -1 -1
3 -1 -1  1  1  1  1 -1 -1
4 -1 -1  0  0  0  0  0 -1
5 -1 -1  0  0  1  1 -1 -1
6 -1 -1  0  0 -1 -1 -1 -1
7 -1 -1 -1 -1 -1 -1 -1 -1

[ frame 16 , win-outome list => [] ]

Placing a 1 piece @ 6 5
Can move left
Can move up
Can move upper-left
Can move upper-left

   0  1  2  3  4  5  6  7
0 -1 -1 -1 -1 -1 -1 -1 -1
1 -1 -1 -1 -1 -1 -1 -1 -1
2 -1 -1  1  1  1  1 -1 -1
3 -1 -1  1  1  1  1 -1 -1
4 -1 -1  0  0  0  1  0 -1
5 -1 -1  0  0  1  1  1 -1
6 -1 -1  0  0 -1 -1 -1 -1
7 -1 -1 -1 -1 -1 -1 -1 -1

[ frame 17 , win-outome list => [] ]

Placing a 0 piece @ 6 3
Can move left
Can move left
Can move left
Can move left
Can move down
Can move upper-left
Can move lower-left
Can move lower-left
Can move lower-left

   0  1  2  3  4  5  6  7
0 -1 -1 -1 -1 -1 -1 -1 -1
1 -1 -1 -1 -1 -1 -1 -1 -1
2 -1 -1  1  1  1  1 -1 -1
3 -1 -1  1  1  1  1  0 -1
4 -1 -1  0  0  0  0  0 -1
5 -1 -1  0  0  0  1  1 -1
6 -1 -1  0  0 -1 -1 -1 -1
7 -1 -1 -1 -1 -1 -1 -1 -1

[ frame 18 , win-outome list => [] ]

Placing a 1 piece @ 4 6
Can move left
Can move left
Can move up
Can move up
Can move up
Can move upper-left
Can move upper-left
Can move upper-right

   0  1  2  3  4  5  6  7
0 -1 -1 -1 -1 -1 -1 -1 -1
1 -1 -1 -1 -1 -1 -1 -1 -1
2 -1 -1  1  1  1  1 -1 -1
3 -1 -1  1  1  1  1  0 -1
4 -1 -1  0  0  1  0  0 -1
5 -1 -1  0  0  1  1  1 -1
6 -1 -1  0  0  1 -1 -1 -1
7 -1 -1 -1 -1 -1 -1 -1 -1

[ frame 19 , win-outome list => [] ]

Placing a 0 piece @ 5 7
Can move upper-left
Can move upper-left

   0  1  2  3  4  5  6  7
0 -1 -1 -1 -1 -1 -1 -1 -1
1 -1 -1 -1 -1 -1 -1 -1 -1
2 -1 -1  1  1  1  1 -1 -1
3 -1 -1  1  1  1  1  0 -1
4 -1 -1  0  0  1  0  0 -1
5 -1 -1  0  0  1  1  1 -1
6 -1 -1  0  0  0 -1 -1 -1
7 -1 -1 -1 -1 -1  0 -1 -1

[ frame 20 , win-outome list => [] ]

Placing a 1 piece @ 7 2
Can move lower-left
Can move lower-left
Can move lower-left

   0  1  2  3  4  5  6  7
0 -1 -1 -1 -1 -1 -1 -1 -1
1 -1 -1 -1 -1 -1 -1 -1 -1
2 -1 -1  1  1  1  1 -1  1
3 -1 -1  1  1  1  1  1 -1
4 -1 -1  0  0  1  1  0 -1
5 -1 -1  0  0  1  1  1 -1
6 -1 -1  0  0  0 -1 -1 -1
7 -1 -1 -1 -1 -1  0 -1 -1

[ frame 21 , win-outome list => [] ]

Placing a 0 piece @ 5 6
Can move left
Can move up
Can move up
Can move up
Can move up
Can move down
Can move upper-left
Can move upper-left
Can move upper-right

   0  1  2  3  4  5  6  7
0 -1 -1 -1 -1 -1 -1 -1 -1
1 -1 -1 -1 -1 -1 -1 -1 -1
2 -1 -1  1  1  1  1 -1  1
3 -1 -1  1  1  1  1  1 -1
4 -1 -1  0  0  1  1  0 -1
5 -1 -1  0  0  0  1  1 -1
6 -1 -1  0  0  0  0 -1 -1
7 -1 -1 -1 -1 -1  0 -1 -1

[ frame 22 , win-outome list => [] ]

Placing a 1 piece @ 7 5
Can move left
Can move upper-left
Can move upper-left

   0  1  2  3  4  5  6  7
0 -1 -1 -1 -1 -1 -1 -1 -1
1 -1 -1 -1 -1 -1 -1 -1 -1
2 -1 -1  1  1  1  1 -1  1
3 -1 -1  1  1  1  1  1 -1
4 -1 -1  0  0  1  1  1 -1
5 -1 -1  0  0  0  1  1  1
6 -1 -1  0  0  0  0 -1 -1
7 -1 -1 -1 -1 -1  0 -1 -1

[ frame 23 , win-outome list => [] ]

Placing a 0 piece @ 4 1
Can move down
Can move down
Can move down
Can move down
Can move lower-left
Can move lower-left
Can move lower-right
Can move lower-right

   0  1  2  3  4  5  6  7
0 -1 -1 -1 -1 -1 -1 -1 -1
1 -1 -1 -1 -1  0 -1 -1 -1
2 -1 -1  1  1  0  1 -1  1
3 -1 -1  1  1  0  1  1 -1
4 -1 -1  0  0  0  1  1 -1
5 -1 -1  0  0  0  1  1  1
6 -1 -1  0  0  0  0 -1 -1
7 -1 -1 -1 -1 -1  0 -1 -1

[ frame 24 , win-outome list => [] ]

Placing a 1 piece @ 5 1
Can move left
Can move down
Can move lower-left
Can move lower-left

   0  1  2  3  4  5  6  7
0 -1 -1 -1 -1 -1 -1 -1 -1
1 -1 -1 -1 -1  0  1 -1 -1
2 -1 -1  1  1  1  1 -1  1
3 -1 -1  1  1  0  1  1 -1
4 -1 -1  0  0  0  1  1 -1
5 -1 -1  0  0  0  1  1  1
6 -1 -1  0  0  0  0 -1 -1
7 -1 -1 -1 -1 -1  0 -1 -1

[ frame 25 , win-outome list => [] ]

Placing a 0 piece @ 1 3
Can move right
Can move right
Can move right
Can move upper-right
Can move lower-right

   0  1  2  3  4  5  6  7
0 -1 -1 -1 -1 -1 -1 -1 -1
1 -1 -1 -1 -1  0  1 -1 -1
2 -1 -1  1  1  1  1 -1  1
3 -1  0  0  0  0  1  1 -1
4 -1 -1  0  0  0  1  1 -1
5 -1 -1  0  0  0  1  1  1
6 -1 -1  0  0  0  0 -1 -1
7 -1 -1 -1 -1 -1  0 -1 -1

[ frame 26 , win-outome list => [] ]

Placing a 1 piece @ 5 0
Can move down
Can move lower-left
Can move lower-left

   0  1  2  3  4  5  6  7
0 -1 -1 -1 -1 -1  1 -1 -1
1 -1 -1 -1 -1  1  1 -1 -1
2 -1 -1  1  1  1  1 -1  1
3 -1  0  0  0  0  1  1 -1
4 -1 -1  0  0  0  1  1 -1
5 -1 -1  0  0  0  1  1  1
6 -1 -1  0  0  0  0 -1 -1
7 -1 -1 -1 -1 -1  0 -1 -1

[ frame 27 , win-outome list => [] ]

Placing a 0 piece @ 6 2
Can move left
Can move left
Can move left
Can move left
Can move right
Can move down
Can move down
Can move down
Can move upper-left
Can move lower-left
Can move lower-left

   0  1  2  3  4  5  6  7
0 -1 -1 -1 -1 -1  1 -1 -1
1 -1 -1 -1 -1  1  1 -1 -1
2 -1 -1  1  1  1  1  0  1
3 -1  0  0  0  0  0  1 -1
4 -1 -1  0  0  0  1  1 -1
5 -1 -1  0  0  0  1  1  1
6 -1 -1  0  0  0  0 -1 -1
7 -1 -1 -1 -1 -1  0 -1 -1

[ frame 28 , win-outome list => [] ]

Placing a 1 piece @ 0 4
Can move upper-right
Can move upper-right

   0  1  2  3  4  5  6  7
0 -1 -1 -1 -1 -1  1 -1 -1
1 -1 -1 -1 -1  1  1 -1 -1
2 -1 -1  1  1  1  1  0  1
3 -1  1  0  0  0  0  1 -1
4  1 -1  0  0  0  1  1 -1
5 -1 -1  0  0  0  1  1  1
6 -1 -1  0  0  0  0 -1 -1
7 -1 -1 -1 -1 -1  0 -1 -1

[ frame 29 , win-outome list => [] ]

Placing a 0 piece @ 0 2
Can move lower-right
Can move lower-right

   0  1  2  3  4  5  6  7
0 -1 -1 -1 -1 -1  1 -1 -1
1 -1 -1 -1 -1  1  1 -1 -1
2  0 -1  1  1  1  1  0  1
3 -1  0  0  0  0  0  1 -1
4  1 -1  0  0  0  1  1 -1
5 -1 -1  0  0  0  1  1  1
6 -1 -1  0  0  0  0 -1 -1
7 -1 -1 -1 -1 -1  0 -1 -1

[ frame 30 , win-outome list => [] ]

Placing a 1 piece @ 0 3
Can move right
Can move right
Can move right
Can move right
Can move right
Can move right
Can move up
Can move down

   0  1  2  3  4  5  6  7
0 -1 -1 -1 -1 -1  1 -1 -1
1 -1 -1 -1 -1  1  1 -1 -1
2  0 -1  1  1  1  1  0  1
3  1  1  1  1  1  1  1 -1
4  1 -1  0  0  0  1  1 -1
5 -1 -1  0  0  0  1  1  1
6 -1 -1  0  0  0  0 -1 -1
7 -1 -1 -1 -1 -1  0 -1 -1

[ frame 31 , win-outome list => [] ]

Placing a 0 piece @ 0 5
Can move up
Can move up
Can move up

   0  1  2  3  4  5  6  7
0 -1 -1 -1 -1 -1  1 -1 -1
1 -1 -1 -1 -1  1  1 -1 -1
2  0 -1  1  1  1  1  0  1
3  0  1  1  1  1  1  1 -1
4  0 -1  0  0  0  1  1 -1
5  0 -1  0  0  0  1  1  1
6 -1 -1  0  0  0  0 -1 -1
7 -1 -1 -1 -1 -1  0 -1 -1

[ frame 32 , win-outome list => [] ]

Placing a 1 piece @ 1 4
Can move left
Can move right
Can move right
Can move right
Can move right
Can move up
Can move upper-left
Can move upper-right
Can move lower-left
Can move lower-right
Can move lower-right

   0  1  2  3  4  5  6  7
0 -1 -1 -1 -1 -1  1 -1 -1
1 -1 -1 -1 -1  1  1 -1 -1
2  0 -1  1  1  1  1  0  1
3  0  1  1  1  1  1  1 -1
4  0  1  1  1  1  1  1 -1
5  0 -1  0  0  0  1  1  1
6 -1 -1  0  0  0  0 -1 -1
7 -1 -1 -1 -1 -1  0 -1 -1

[ frame 33 , win-outome list => [] ]

Placing a 0 piece @ 7 4
Can move left
Can move left
Can move left
Can move left
Can move left
Can move left
Can move left
Can move down
Can move upper-left
Can move upper-left
Can move upper-left
Can move lower-left
Can move lower-left

   0  1  2  3  4  5  6  7
0 -1 -1 -1 -1 -1  1 -1 -1
1 -1 -1 -1 -1  1  1 -1 -1
2  0 -1  1  1  1  1  0  1
3  0  1  1  1  1  1  1 -1
4  0  0  0  0  0  0  0  0
5  0 -1  0  0  0  1  0  1
6 -1 -1  0  0  0  0 -1 -1
7 -1 -1 -1 -1 -1  0 -1 -1

[ frame 34 , win-outome list => [] ]

Placing a 1 piece @ 7 3
Can move left
Can move up
Can move down
Can move down
Can move upper-left
Can move upper-left
Can move lower-left
Can move lower-left

   0  1  2  3  4  5  6  7
0 -1 -1 -1 -1 -1  1 -1 -1
1 -1 -1 -1 -1  1  1 -1 -1
2  0 -1  1  1  1  1  1  1
3  0  1  1  1  1  1  1  1
4  0  0  0  0  0  0  1  1
5  0 -1  0  0  0  1  0  1
6 -1 -1  0  0  0  0 -1 -1
7 -1 -1 -1 -1 -1  0 -1 -1

[ frame 35 , win-outome list => [] ]

Placing a 0 piece @ 1 2
Can move left
Can move right
Can move right
Can move right
Can move right
Can move right
Can move right
Can move down
Can move down
Can move lower-left
Can move lower-right
Can move lower-right

   0  1  2  3  4  5  6  7
0 -1 -1 -1 -1 -1  1 -1 -1
1 -1 -1 -1 -1  1  1 -1 -1
2  0  0  1  1  1  1  1  1
3  0  0  0  1  1  1  1  1
4  0  0  0  0  0  0  1  1
5  0 -1  0  0  0  1  0  1
6 -1 -1  0  0  0  0 -1 -1
7 -1 -1 -1 -1 -1  0 -1 -1

[ frame 36 , win-outome list => [] ]

Placing a 1 piece @ 1 5
Can move left
Can move right
Can move right
Can move right
Can move right
Can move up
Can move up
Can move up
Can move upper-left
Can move upper-right
Can move upper-right
Can move lower-right

   0  1  2  3  4  5  6  7
0 -1 -1 -1 -1 -1  1 -1 -1
1 -1 -1 -1 -1  1  1 -1 -1
2  0  0  1  1  1  1  1  1
3  0  0  0  1  1  1  1  1
4  0  0  1  0  0  0  1  1
5  0  1  1  1  1  1  0  1
6 -1 -1  0  0  0  0 -1 -1
7 -1 -1 -1 -1 -1  0 -1 -1

[ frame 37 , win-outome list => [] ]

Placing a 0 piece @ 2 1
Can move down
Can move down
Can move lower-left
Can move lower-right
Can move lower-right
Can move lower-right

   0  1  2  3  4  5  6  7
0 -1 -1 -1 -1 -1  1 -1 -1
1 -1 -1  0 -1  1  1 -1 -1
2  0  0  0  0  1  1  1  1
3  0  0  0  1  0  1  1  1
4  0  0  1  0  0  0  1  1
5  0  1  1  1  1  1  0  1
6 -1 -1  0  0  0  0 -1 -1
7 -1 -1 -1 -1 -1  0 -1 -1

[ frame 38 , win-outome list => [] ]

Placing a 1 piece @ 2 0
Can move down
Can move down
Can move down
Can move down

   0  1  2  3  4  5  6  7
0 -1 -1  1 -1 -1  1 -1 -1
1 -1 -1  1 -1  1  1 -1 -1
2  0  0  1  0  1  1  1  1
3  0  0  1  1  0  1  1  1
4  0  0  1  0  0  0  1  1
5  0  1  1  1  1  1  0  1
6 -1 -1  0  0  0  0 -1 -1
7 -1 -1 -1 -1 -1  0 -1 -1

[ frame 39 , win-outome list => [] ]

Placing a 0 piece @ 3 1
Can move left
Can move right
Can move right
Can move down
Can move upper-left
Can move lower-left
Can move lower-left
Can move lower-right
Can move lower-right
Can move lower-right
Can move lower-right

   0  1  2  3  4  5  6  7
0 -1 -1  1 -1 -1  1 -1 -1
1 -1 -1  1  0  1  1 -1 -1
2  0  0  0  0  1  1  1  1
3  0  0  1  1  0  1  1  1
4  0  0  1  0  0  0  1  1
5  0  1  1  1  1  1  0  1
6 -1 -1  0  0  0  0 -1 -1
7 -1 -1 -1 -1 -1  0 -1 -1

[ frame 40 , win-outome list => [] ]

Placing a 1 piece @ 2 7
Can move up
Can move up
Can move upper-right
Can move upper-right

   0  1  2  3  4  5  6  7
0 -1 -1  1 -1 -1  1 -1 -1
1 -1 -1  1  0  1  1 -1 -1
2  0  0  0  0  1  1  1  1
3  0  0  1  1  0  1  1  1
4  0  0  1  0  0  0  1  1
5  0  1  1  1  1  1  0  1
6 -1 -1  1  1  0  0 -1 -1
7 -1 -1  1 -1 -1  0 -1 -1

[ frame 41 , win-outome list => [] ]

Placing a 0 piece @ 3 7
Can move left
Can move up
Can move up
Can move up
Can move upper-left
Can move upper-left
Can move upper-left
Can move upper-right

   0  1  2  3  4  5  6  7
0 -1 -1  1 -1 -1  1 -1 -1
1 -1 -1  1  0  1  1 -1 -1
2  0  0  0  0  1  1  1  1
3  0  0  1  1  0  1  1  1
4  0  0  1  0  0  0  1  1
5  0  0  1  0  1  1  0  1
6 -1 -1  0  0  0  0 -1 -1
7 -1 -1  1  0 -1  0 -1 -1

[ frame 42 , win-outome list => [] ]

Placing a 1 piece @ 3 0
Can move left
Can move down
Can move down
Can move down
Can move lower-left
Can move lower-right

   0  1  2  3  4  5  6  7
0 -1 -1  1  1 -1  1 -1 -1
1 -1 -1  1  1  1  1 -1 -1
2  0  0  0  1  1  1  1  1
3  0  0  1  1  0  1  1  1
4  0  0  1  0  0  0  1  1
5  0  0  1  0  1  1  0  1
6 -1 -1  0  0  0  0 -1 -1
7 -1 -1  1  0 -1  0 -1 -1

[ frame 43 , win-outome list => [] ]

Placing a 0 piece @ 4 0
Can move left
Can move left
Can move right
Can move down
Can move down
Can move down
Can move lower-left
Can move lower-left
Can move lower-right
Can move lower-right
Can move lower-right

   0  1  2  3  4  5  6  7
0 -1 -1  1  1  0  1 -1 -1
1 -1 -1  1  0  0  1 -1 -1
2  0  0  0  1  0  1  1  1
3  0  0  1  1  0  1  1  1
4  0  0  1  0  0  0  1  1
5  0  0  1  0  1  1  0  1
6 -1 -1  0  0  0  0 -1 -1
7 -1 -1  1  0 -1  0 -1 -1

[ frame 44 , win-outome list => [] ]

Placing a 1 piece @ 7 6
Can move up
Can move upper-left
Can move upper-left
Can move upper-left
Can move upper-left

   0  1  2  3  4  5  6  7
0 -1 -1  1  1  0  1 -1 -1
1 -1 -1  1  0  0  1 -1 -1
2  0  0  0  1  0  1  1  1
3  0  0  1  1  1  1  1  1
4  0  0  1  0  0  1  1  1
5  0  0  1  0  1  1  1  1
6 -1 -1  0  0  0  0 -1  1
7 -1 -1  1  0 -1  0 -1 -1

[ frame 45 , win-outome list => [] ]

Placing a 0 piece @ 6 1
Can move left
Can move left
Can move down
Can move down
Can move down
Can move down
Can move upper-left
Can move lower-left
Can move lower-left
Can move lower-left
Can move lower-right

   0  1  2  3  4  5  6  7
0 -1 -1  1  1  0  1 -1 -1
1 -1 -1  1  0  0  0  0 -1
2  0  0  0  1  0  0  1  1
3  0  0  1  1  0  1  1  1
4  0  0  1  0  0  1  1  1
5  0  0  1  0  1  1  1  1
6 -1 -1  0  0  0  0 -1  1
7 -1 -1  1  0 -1  0 -1 -1

[ frame 46 , win-outome list => [] ]

Placing a 1 piece @ 7 1
Can move left
Can move left
Can move left
Can move left
Can move left
Can move down
Can move lower-left

   0  1  2  3  4  5  6  7
0 -1 -1  1  1  0  1 -1 -1
1 -1 -1  1  1  1  1  1  1
2  0  0  0  1  0  0  1  1
3  0  0  1  1  0  1  1  1
4  0  0  1  0  0  1  1  1
5  0  0  1  0  1  1  1  1
6 -1 -1  0  0  0  0 -1  1
7 -1 -1  1  0 -1  0 -1 -1

[ frame 47 , win-outome list => [] ]

Placing a 0 piece @ 7 0
Can move down
Can move down
Can move down
Can move down
Can move down
Can move down
Can move lower-left
Can move lower-left

   0  1  2  3  4  5  6  7
0 -1 -1  1  1  0  1 -1  0
1 -1 -1  1  1  1  1  0  1
2  0  0  0  1  0  0  1  1
3  0  0  1  1  0  1  1  1
4  0  0  1  0  0  1  1  1
5  0  0  1  0  1  1  1  1
6 -1 -1  0  0  0  0 -1  1
7 -1 -1  1  0 -1  0 -1 -1

[ frame 48 , win-outome list => [] ]

Placing a 1 piece @ 6 0
Can move left
Can move right
Can move down
Can move down
Can move lower-left
Can move lower-right

   0  1  2  3  4  5  6  7
0 -1 -1  1  1  0  1  1  0
1 -1 -1  1  1  1  1  1  1
2  0  0  0  1  0  0  1  1
3  0  0  1  1  0  1  1  1
4  0  0  1  0  0  1  1  1
5  0  0  1  0  1  1  1  1
6 -1 -1  0  0  0  0 -1  1
7 -1 -1  1  0 -1  0 -1 -1

[ frame 49 , win-outome list => [] ]

Placing a 0 piece @ 7 7
Can move up
Can move up
Can move up
Can move up
Can move up
Can move up
Can move up

   0  1  2  3  4  5  6  7
0 -1 -1  1  1  0  1  1  0
1 -1 -1  1  1  1  1  1  0
2  0  0  0  1  0  0  1  0
3  0  0  1  1  0  1  1  0
4  0  0  1  0  0  1  1  0
5  0  0  1  0  1  1  1  0
6 -1 -1  0  0  0  0 -1  0
7 -1 -1  1  0 -1  0 -1  0

[ frame 50 , win-outome list => [] ]

Placing a 1 piece @ 1 1
Can move right
Can move down
Can move down
Can move down
Can move down
Can move upper-right
Can move lower-left
Can move lower-right
Can move lower-right

   0  1  2  3  4  5  6  7
0 -1 -1  1  1  0  1  1  0
1 -1  1  1  1  1  1  1  0
2  0  0  1  1  0  0  1  0
3  0  0  1  1  0  1  1  0
4  0  0  1  0  0  1  1  0
5  0  0  1  0  1  1  1  0
6 -1 -1  0  0  0  0 -1  0
7 -1 -1  1  0 -1  0 -1  0

[ frame 51 , win-outome list => [] ]

Placing a 0 piece @ 0 1
Can move right
Can move right
Can move right
Can move right
Can move right
Can move right
Can move right
Can move down
Can move lower-right

   0  1  2  3  4  5  6  7
0 -1 -1  1  1  0  1  1  0
1  0  0  0  0  0  0  0  0
2  0  0  1  1  0  0  1  0
3  0  0  1  1  0  1  1  0
4  0  0  1  0  0  1  1  0
5  0  0  1  0  1  1  1  0
6 -1 -1  0  0  0  0 -1  0
7 -1 -1  1  0 -1  0 -1  0

[ frame 52 , win-outome list => [] ]

Placing a 1 piece @ 0 0
Can move down
Can move down
Can move down
Can move down
Can move down
Can move lower-right
Can move lower-right

   0  1  2  3  4  5  6  7
0  1 -1  1  1  0  1  1  0
1  0  1  0  0  0  0  0  0
2  0  0  1  1  0  0  1  0
3  0  0  1  1  0  1  1  0
4  0  0  1  0  0  1  1  0
5  0  0  1  0  1  1  1  0
6 -1 -1  0  0  0  0 -1  0
7 -1 -1  1  0 -1  0 -1  0

[ frame 53 , win-outome list => [] ]

Placing a 0 piece @ 1 0
Can move left
Can move right
Can move right
Can move right
Can move down
Can move down
Can move lower-left
Can move lower-right

   0  1  2  3  4  5  6  7
0  1  0  0  0  0  1  1  0
1  0  0  0  0  0  0  0  0
2  0  0  1  1  0  0  1  0
3  0  0  1  1  0  1  1  0
4  0  0  1  0  0  1  1  0
5  0  0  1  0  1  1  1  0
6 -1 -1  0  0  0  0 -1  0
7 -1 -1  1  0 -1  0 -1  0

[ frame 54 , win-outome list => [] ]

Placing a 1 piece @ 0 6
Can move up
Can move up
Can move up
Can move up
Can move up
Can move up
Can move upper-right
Can move upper-right

   0  1  2  3  4  5  6  7
0  1  0  0  0  0  1  1  0
1  1  0  0  0  0  0  0  0
2  1  0  1  1  0  0  1  0
3  1  0  1  1  0  1  1  0
4  1  0  1  0  0  1  1  0
5  1  1  1  0  1  1  1  0
6  1 -1  0  0  0  0 -1  0
7 -1 -1  1  0 -1  0 -1  0

[ frame 55 , win-outome list => [] ]

Placing a 0 piece @ 1 6
Can move left
Can move right
Can move up
Can move up
Can move upper-left
Can move upper-right
Can move upper-right
Can move lower-right

   0  1  2  3  4  5  6  7
0  1  0  0  0  0  1  1  0
1  1  0  0  0  0  0  0  0
2  1  0  1  1  0  0  1  0
3  1  0  1  1  0  1  1  0
4  1  0  1  0  0  1  1  0
5  1  0  0  0  1  1  1  0
6  1  0  0  0  0  0 -1  0
7 -1 -1  1  0 -1  0 -1  0

[ frame 56 , win-outome list => [] ]

Placing a 1 piece @ 4 7
Can move left
Can move left
Can move right
Can move up
Can move up
Can move upper-left
Can move upper-left
Can move upper-left
Can move upper-left
Can move upper-right
Can move upper-right

   0  1  2  3  4  5  6  7
0  1  0  0  0  0  1  1  0
1  1  0  0  0  0  0  0  0
2  1  0  1  1  0  0  1  0
3  1  0  1  1  0  1  1  0
4  1  1  1  0  0  1  1  0
5  1  0  1  0  1  1  1  0
6  1  0  0  1  1  1 -1  0
7 -1 -1  1  1  1  0 -1  0

[ frame 57 , win-outome list => [] ]

Placing a 0 piece @ 1 7
Can move right
Can move right
Can move right
Can move right
Can move up
Can move upper-left
Can move upper-right

   0  1  2  3  4  5  6  7
0  1  0  0  0  0  1  1  0
1  1  0  0  0  0  0  0  0
2  1  0  1  1  0  0  1  0
3  1  0  1  1  0  1  1  0
4  1  1  1  0  0  1  1  0
5  1  0  1  0  1  1  1  0
6  1  0  0  1  1  1 -1  0
7 -1  0  0  0  0  0 -1  0

[ frame 58 , win-outome list => [] ]

Placing a 1 piece @ 0 7
Can move right
Can move right
Can move right
Can move right
Can move right
Can move up
Can move upper-right
Can move upper-right

   0  1  2  3  4  5  6  7
0  1  0  0  0  0  1  1  0
1  1  0  0  0  0  0  0  0
2  1  0  1  1  0  0  1  0
3  1  0  1  1  0  1  1  0
4  1  1  1  0  0  1  1  0
5  1  0  1  0  1  1  1  0
6  1  1  0  1  1  1 -1  0
7  1  0  0  0  0  0 -1  0

[ frame 59 , win-outome list => [] ]

Placing a 0 piece @ 6 7
Can move left
Can move right
Can move upper-left
Can move upper-left
Can move upper-left
Can move upper-right

   0  1  2  3  4  5  6  7
0  1  0  0  0  0  1  1  0
1  1  0  0  0  0  0  0  0
2  1  0  1  1  0  0  1  0
3  1  0  1  1  0  1  1  0
4  1  1  1  0  0  1  1  0
5  1  0  1  0  0  1  1  0
6  1  1  0  1  1  0 -1  0
7  1  0  0  0  0  0  0  0

[ frame 60 , win-outome list => [] ]

Placing a 1 piece @ 6 6
Can move left
Can move left
Can move right
Can move up
Can move down
Can move upper-left
Can move upper-right
Can move lower-left
Can move lower-right

   0  1  2  3  4  5  6  7
0  1  0  0  0  0  1  1  0
1  1  0  0  0  0  0  0  0
2  1  0  1  1  0  0  1  0
3  1  0  1  1  0  1  1  0
4  1  1  1  0  0  1  1  0
5  1  0  1  0  0  1  1  0
6  1  1  0  1  1  1  1  0
7  1  0  0  0  0  0  0  0

[ frame 61 , win-outome list => [] ]

In [200]:
# Label last frame in curr_board_states with definite win/lose
# Then run through curr_board_states once, and hash it, and store in db.

final_outcome = -1  # 0 = black wins, 1 = black loses, 2 = draw

black_count = 0
white_count = 0

count = curr_game_states.get_count()
last_state = curr_game_states.get_board_state_obj_list()[count-1].get_board_state()

for i in range(8):
    for j in range(8):
        if last_state[i][j] == 0:
            black_count = black_count + 1
        elif last_state[i][j] == 1:
            white_count = white_count + 1
if black_count == white_count:
    final_outcome = 2
elif black_count < white_count:
    final_outcome = 1
elif black_count > white_count:
    final_outcome = 0
else:
    print("Error: final_outcome out of range.", file=sys.stderr)           
                
try:
    with open("othello_game_states.pickle","rb") as pickle_in:
        print("loading existing othello_game_states.pickle file")
        db_game_states_dict = pk.load(pickle_in)
        
        for temp_state in curr_game_states.get_board_state_obj_list():
            # Construct a key from board layout and then save board layout obj under it
            temp_grid = temp_state.get_board_state()
            temp_key = []
            for i in range(8):
                for j in range(8):
                    temp_key.append(str(temp_grid[i][j]))
            key = ''.join(temp_key)
            
            if key in db_game_states_dict.keys():
                print("Duplicate found!")
                # db_temp_state is the state from file with the same layout as the one in mem.
                # But only the file state will be updated.
                db_temp_state = db_game_states_dict[key]
                db_temp_state.add_win_outcome_to_list(final_outcome)
                db_game_states_dict[key] = db_temp_state
                
            else:
                temp_state_copy = copy.deepcopy(temp_state)
                temp_state_copy.add_win_outcome_to_list(final_outcome)
                db_game_states_dict[key] = temp_state_copy
                
    with open("othello_game_states.pickle","wb") as pickle_out:
        pk.dump(db_game_states_dict, pickle_out)
except IOError:  # The file cannot be opened, or does not exist - initialize new one
    print("creating new othello_game_states.pickle file")
    with open("othello_game_states.pickle","wb") as pickle_out:
        for temp_state in curr_game_states.get_board_state_obj_list():
            # Construct a key from board layout and then save board layout obj under it
            temp_grid = temp_state.get_board_state()
            temp_key = []
            for i in range(8):
                for j in range(8):
                    temp_key.append(str(temp_grid[i][j]))
            key = ''.join(temp_key)
            
            # add an additional outcome (the current outcome) to temp_state
            # Check for error with Python variable binding
            temp_state_copy = copy.deepcopy(temp_state)
            temp_state_copy.add_win_outcome_to_list(final_outcome)
            new_game_states_dict[key] = temp_state_copy
        pk.dump(new_game_states_dict, pickle_out)
except EOFError:
    print("Caught EOFError, corrupt pickle file?", file=sys.stderr)

loading existing othello_game_states.pickle file
Duplicate found!
Duplicate found!
Duplicate found!
Duplicate found!
Duplicate found!
Duplicate found!